### ISSUE TITLE
Viewer options

### ISSUE THREAD

**Issue by outpaddling** [hwm2746/brain-mesh-builder#5]
I wonder if it might be feasible to use a more open and portable viewer in place of vmd?  vmd is a bit of a headache, as it requires registration to download and works only on certain CPU types.  I'm pretty clueless about viewers.  Just wondering if it's possible to remove this hurdle for some users.

**Comment by acchangg12** [comment]
We can look into this. VMD is just what we are used to working with and is really helpful with debugging, since we can view specific filaments/beads by individual or group labels. 

However, we do have two ways around using VMD:
1. Write to image options for both bead3d and fnet3d, so the BOC model can be viewed in image slices for quick/easy checking. This would be called as:
_bead3d write name outfile format png bead_size 1_ 

2. Write to .stl file. This file type is common for viewing 3D models, and can be opened with free CAD software such as MeshLab. We placed an example of this in the test folder under wt_fixed/zf_mesh.inp, and the STL file is wt_fixed/out/fwt.stl 

Hope this helps.

**Comment by outpaddling** [comment]
My bad, I overlooked the STL option in the READMEs.  MeshLab seems very good to me.  Fully open source, fast, intuitive and polished interface.  I wouldn't know if it's short on features, though, as I'm not a brain scientist.

FYI, it would be good if you could restore the test inputs in the next release.  I'm not seeing another way to access them besides an older release.  I was only suggesting removing the *outputs* and binaries to reduce the size of the dist.

Thanks...
